spring:
  application:
    name: ProgressPulse
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 8081
progress-pulse:
  security:
    jwt:
      secret-key: 341324901734591243732145514234234523543t214654hgwywy5ywtgrt135yyhgyhsarghwgh
